import Head from "next/head";

import "../styles/globals.css";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Mindfulness | Clear your mind with us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/svg+xml" href="/logo.svg" />
        <link rel="mask-icon" href="/logo.svg" color="#ff8a01" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
